
version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/bus-booking
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_REFRESH_SECRET=your-super-secret-refresh-jwt-key-change-in-production
      - FRONTEND_URL=http://localhost:8080
    depends_on:
      - mongo
    networks:
      - bus-booking-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=bus-booking
    networks:
      - bus-booking-network

networks:
  bus-booking-network:
    driver: bridge

volumes:
  mongo-data:
